apiVersion: apps/v1
kind: Deployment
metadata:
  name: nardly-website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nardly-website
  template:
    metadata:
      labels:
        app: nardly-website
    spec:
      containers:
      - name: nardly
        image: maynarddomingo/brownbag-08042025:latest
        ports:
        - containerPort: 8090
---
apiVersion: v1
kind: Service
metadata:
  name: nardly-website-svc
spec:
  type: LoadBalancer
  selector:
    app: nardly-website
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
